//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loregroup.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateNewCompanyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateNewCompanyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loregroup.Core.Resource.CreateNewCompanyResource", typeof(CreateNewCompanyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Company.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        public static string Addressline1 {
            get {
                return ResourceManager.GetString("Addressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        public static string Addressline2 {
            get {
                return ResourceManager.GetString("Addressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 3.
        /// </summary>
        public static string Addressline3 {
            get {
                return ResourceManager.GetString("Addressline3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string amountsign {
            get {
                return ResourceManager.GetString("amountsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Information.
        /// </summary>
        public static string AreaInformation {
            get {
                return ResourceManager.GetString("AreaInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Afterwards.
        /// </summary>
        public static string ChargesAfterwards {
            get {
                return ResourceManager.GetString("ChargesAfterwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Breakdown.
        /// </summary>
        public static string ChargesBreakdown {
            get {
                return ResourceManager.GetString("ChargesBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ABC Package Information.
        /// </summary>
        public static string CompanyABCPackageInformation {
            get {
                return ResourceManager.GetString("CompanyABCPackageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ABC Site Information.
        /// </summary>
        public static string CompanyABCSiteInformation {
            get {
                return ResourceManager.GetString("CompanyABCSiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Communication Email ID.
        /// </summary>
        public static string CompanyCommunicationEmailID {
            get {
                return ResourceManager.GetString("CompanyCommunicationEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Contact Info.
        /// </summary>
        public static string CompanyContactInfo {
            get {
                return ResourceManager.GetString("CompanyContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        public static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Cost.
        /// </summary>
        public static string DeploymentCost {
            get {
                return ResourceManager.GetString("DeploymentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Time Period.
        /// </summary>
        public static string EnterTimePeriod {
            get {
                return ResourceManager.GetString("EnterTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Procedure Available.
        /// </summary>
        public static string FreeProcedureAvailable {
            get {
                return ResourceManager.GetString("FreeProcedureAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Type.
        /// </summary>
        public static string IndustryType {
            get {
                return ResourceManager.GetString("IndustryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice and Reminders Details.
        /// </summary>
        public static string InvoiceandRemindersDetails {
            get {
                return ResourceManager.GetString("InvoiceandRemindersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep 1 copy of sent invoice to DFO mailbox.
        /// </summary>
        public static string Keep1copyofsentinvoicetoDFOmailbox {
            get {
                return ResourceManager.GetString("Keep1copyofsentinvoicetoDFOmailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep 1 copy of sent invoice to Notification row.
        /// </summary>
        public static string Keep1copyofsentinvoicetoNotificationrow {
            get {
                return ResourceManager.GetString("Keep1copyofsentinvoicetoNotificationrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Scheme.
        /// </summary>
        public static string LicenseScheme {
            get {
                return ResourceManager.GetString("LicenseScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Of Payment.
        /// </summary>
        public static string ModeOfPayment {
            get {
                return ResourceManager.GetString("ModeOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Information.
        /// </summary>
        public static string PackageInformation {
            get {
                return ResourceManager.GetString("PackageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment History.
        /// </summary>
        public static string PaymentHistory {
            get {
                return ResourceManager.GetString("PaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Schedule.
        /// </summary>
        public static string PaymentSchedule {
            get {
                return ResourceManager.GetString("PaymentSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Scheduled.
        /// </summary>
        public static string PaymentScheduled {
            get {
                return ResourceManager.GetString("PaymentScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Procedure Charges.
        /// </summary>
        public static string PerProcedureCharges {
            get {
                return ResourceManager.GetString("PerProcedureCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop-up Payment Reminder.
        /// </summary>
        public static string PopupPaymentReminder {
            get {
                return ResourceManager.GetString("PopupPaymentReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Email.
        /// </summary>
        public static string PrimaryEmail {
            get {
                return ResourceManager.GetString("PrimaryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Phone.
        /// </summary>
        public static string PrimaryPhone {
            get {
                return ResourceManager.GetString("PrimaryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Department.
        /// </summary>
        public static string ProductionDepartment {
            get {
                return ResourceManager.GetString("ProductionDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me Before.
        /// </summary>
        public static string RemindMeBefore {
            get {
                return ResourceManager.GetString("RemindMeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Email.
        /// </summary>
        public static string SecondaryEmail {
            get {
                return ResourceManager.GetString("SecondaryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Phone.
        /// </summary>
        public static string SecondaryPhone {
            get {
                return ResourceManager.GetString("SecondaryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send 1 copy of sent invoice to MYOB.
        /// </summary>
        public static string Send1copyofsentinvoicetoMYOB {
            get {
                return ResourceManager.GetString("Send1copyofsentinvoicetoMYOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invoice Automatically.
        /// </summary>
        public static string SendInvoiceAutomatically {
            get {
                return ResourceManager.GetString("SendInvoiceAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invoice Before.
        /// </summary>
        public static string SendInvoiceBefore {
            get {
                return ResourceManager.GetString("SendInvoiceBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitewise Billing Amount.
        /// </summary>
        public static string SitewiseBillingAmount {
            get {
                return ResourceManager.GetString("SitewiseBillingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of Sites.
        /// </summary>
        public static string TotalnumberofSites {
            get {
                return ResourceManager.GetString("TotalnumberofSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Statistics.
        /// </summary>
        public static string UsageStatistics {
            get {
                return ResourceManager.GetString("UsageStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White label System.
        /// </summary>
        public static string WhitelabelSystem {
            get {
                return ResourceManager.GetString("WhitelabelSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
