//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loregroup.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailSettingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailSettingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loregroup.Core.Resource.EmailSettingResource", typeof(EmailSettingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Test Email.
        /// </summary>
        public static string btnInsertTestEmail {
            get {
                return ResourceManager.GetString("btnInsertTestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Now.
        /// </summary>
        public static string btnProcessnow {
            get {
                return ResourceManager.GetString("btnProcessnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Account Setting...
        /// </summary>
        public static string btnTestAccountSetting {
            get {
                return ResourceManager.GetString("btnTestAccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Settings....
        /// </summary>
        public static string buttonMoreSetting {
            get {
                return ResourceManager.GetString("buttonMoreSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Password.
        /// </summary>
        public static string EmailPassword {
            get {
                return ResourceManager.GetString("EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Server Setting.
        /// </summary>
        public static string EmailServerSetting {
            get {
                return ResourceManager.GetString("EmailServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Mail Server.
        /// </summary>
        public static string IncomingMailserver {
            get {
                return ResourceManager.GetString("IncomingMailserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon Information.
        /// </summary>
        public static string LogonInformation {
            get {
                return ResourceManager.GetString("LogonInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing mail server(SMTP).
        /// </summary>
        public static string Outgoingmailserver {
            get {
                return ResourceManager.GetString("Outgoingmailserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        public static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require logon using Secure Password Authantication(SPA).
        /// </summary>
        public static string requirelogon {
            get {
                return ResourceManager.GetString("requirelogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send New Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Information.
        /// </summary>
        public static string ServerInformation {
            get {
                return ResourceManager.GetString("ServerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Account Setting.
        /// </summary>
        public static string TestaccountSetting {
            get {
                return ResourceManager.GetString("TestaccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Emails in the Queue:.
        /// </summary>
        public static string totalEmailinQueue {
            get {
                return ResourceManager.GetString("totalEmailinQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Emails Sent:.
        /// </summary>
        public static string totalEmailsent {
            get {
                return ResourceManager.GetString("totalEmailsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
