//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loregroup.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LicenseSettingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LicenseSettingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loregroup.Core.Resource.LicenseSettingResource", typeof(LicenseSettingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Disable at end date.
        /// </summary>
        public static string AutoDisable {
            get {
                return ResourceManager.GetString("AutoDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Disable at end date.
        /// </summary>
        public static string AutoDisableatenddate {
            get {
                return ResourceManager.GetString("AutoDisableatenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Version.
        /// </summary>
        public static string CommercialVersion {
            get {
                return ResourceManager.GetString("CommercialVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Version.
        /// </summary>
        public static string CorporateVersion {
            get {
                return ResourceManager.GetString("CorporateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Version.
        /// </summary>
        public static string EnterpriseVersion {
            get {
                return ResourceManager.GetString("EnterpriseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Procedures.
        /// </summary>
        public static string FreeProcedures {
            get {
                return ResourceManager.GetString("FreeProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Scheme.
        /// </summary>
        public static string LicenseScheme {
            get {
                return ResourceManager.GetString("LicenseScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of AppUsers.
        /// </summary>
        public static string NoOfAppUsers {
            get {
                return ResourceManager.GetString("NoOfAppUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Published Procedures Charges:.
        /// </summary>
        public static string PerPublishedProceduresCharges {
            get {
                return ResourceManager.GetString("PerPublishedProceduresCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Details.
        /// </summary>
        public static string PlanDetail {
            get {
                return ResourceManager.GetString("PlanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Provided.
        /// </summary>
        public static string RoleProvided {
            get {
                return ResourceManager.GetString("RoleProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role Status Active.
        /// </summary>
        public static string RoleStatusSelection {
            get {
                return ResourceManager.GetString("RoleStatusSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send end Reminder at.
        /// </summary>
        public static string Sendreminderat {
            get {
                return ResourceManager.GetString("Sendreminderat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Available.
        /// </summary>
        public static string ServiceAvailable {
            get {
                return ResourceManager.GetString("ServiceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Charges.
        /// </summary>
        public static string ServiceCharges {
            get {
                return ResourceManager.GetString("ServiceCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Schemes.
        /// </summary>
        public static string SubscriptionSchemes {
            get {
                return ResourceManager.GetString("SubscriptionSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Schemes Name:.
        /// </summary>
        public static string SubscriptionSchemesName {
            get {
                return ResourceManager.GetString("SubscriptionSchemesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Duration.
        /// </summary>
        public static string TimeDuration {
            get {
                return ResourceManager.GetString("TimeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send trail end reminder at.
        /// </summary>
        public static string trailEndReminder {
            get {
                return ResourceManager.GetString("trailEndReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail Version.
        /// </summary>
        public static string TrailVersion {
            get {
                return ResourceManager.GetString("TrailVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Description.
        /// </summary>
        public static string UserDescription {
            get {
                return ResourceManager.GetString("UserDescription", resourceCulture);
            }
        }
    }
}
