//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loregroup.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loregroup.Core.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Materials.
        /// </summary>
        internal static string AddMaterials {
            get {
                return ResourceManager.GetString("AddMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Properties.
        /// </summary>
        internal static string AddProperty {
            get {
                return ResourceManager.GetString("AddProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Signature.
        /// </summary>
        internal static string AddSignature {
            get {
                return ResourceManager.GetString("AddSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation.
        /// </summary>
        internal static string Affiliation {
            get {
                return ResourceManager.GetString("Affiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill Affiliation..
        /// </summary>
        internal static string AffiliationValidation {
            get {
                return ResourceManager.GetString("AffiliationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Technique.
        /// </summary>
        internal static string AnalysisTechnique {
            get {
                return ResourceManager.GetString("AnalysisTechnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        internal static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Images.
        /// </summary>
        internal static string BannerImages {
            get {
                return ResourceManager.GetString("BannerImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box 1 Content.
        /// </summary>
        internal static string Box1Content {
            get {
                return ResourceManager.GetString("Box1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box 2 Content.
        /// </summary>
        internal static string Box2Content {
            get {
                return ResourceManager.GetString("Box2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box 3 Content.
        /// </summary>
        internal static string Box3Content {
            get {
                return ResourceManager.GetString("Box3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box 4 Content.
        /// </summary>
        internal static string Box4Content {
            get {
                return ResourceManager.GetString("Box4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business View Model must be less 50 word..
        /// </summary>
        internal static string BusinessViewModelValidation {
            get {
                return ResourceManager.GetString("BusinessViewModelValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select bussness Id..
        /// </summary>
        internal static string BussnessPleaseSelect {
            get {
                return ResourceManager.GetString("BussnessPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Banner.
        /// </summary>
        internal static string ButtonAddNewBanner {
            get {
                return ResourceManager.GetString("ButtonAddNewBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Banner.
        /// </summary>
        internal static string ButtonDeleteBanner {
            get {
                return ResourceManager.GetString("ButtonDeleteBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Social Widget.
        /// </summary>
        internal static string ButtonDeleteSocialWidget {
            get {
                return ResourceManager.GetString("ButtonDeleteSocialWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Why ES.
        /// </summary>
        internal static string buttonDeleteWhyes {
            get {
                return ResourceManager.GetString("buttonDeleteWhyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Social Widget.
        /// </summary>
        internal static string ButtonSocialWidget {
            get {
                return ResourceManager.GetString("ButtonSocialWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select City..
        /// </summary>
        internal static string CityPleaseSelect {
            get {
                return ResourceManager.GetString("CityPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities.
        /// </summary>
        internal static string Communities {
            get {
                return ResourceManager.GetString("Communities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Company..
        /// </summary>
        internal static string CompanyValidation {
            get {
                return ResourceManager.GetString("CompanyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select countries name..
        /// </summary>
        internal static string Countriesvalidation {
            get {
                return ResourceManager.GetString("Countriesvalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Country..
        /// </summary>
        internal static string CountryPleaseSelect {
            get {
                return ResourceManager.GetString("CountryPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Department..
        /// </summary>
        internal static string DepartmentPleaseSelect {
            get {
                return ResourceManager.GetString("DepartmentPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Validation..
        /// </summary>
        internal static string DepartmentValidation {
            get {
                return ResourceManager.GetString("DepartmentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less 250 word..
        /// </summary>
        internal static string DescriptionValidation {
            get {
                return ResourceManager.GetString("DescriptionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Address.
        /// </summary>
        internal static string DesertfireAddress {
            get {
                return ResourceManager.GetString("DesertfireAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory Address.
        /// </summary>
        internal static string DesertfireLaboratoryAddress {
            get {
                return ResourceManager.GetString("DesertfireLaboratoryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Designation..
        /// </summary>
        internal static string DesignationPleaseSelect {
            get {
                return ResourceManager.GetString("DesignationPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Username must be less 50 word..
        /// </summary>
        internal static string DesiredUsernameValidation {
            get {
                return ResourceManager.GetString("DesiredUsernameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid email address is required..
        /// </summary>
        internal static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Title.
        /// </summary>
        internal static string FacebookTitle {
            get {
                return ResourceManager.GetString("FacebookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Redirect Url.
        /// </summary>
        internal static string FacebookUrl {
            get {
                return ResourceManager.GetString("FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Detail ViewModels.
        /// </summary>
        internal static string FileDetailViewModels {
            get {
                return ResourceManager.GetString("FileDetailViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiile Type.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName must be less 25 word..
        /// </summary>
        internal static string FirstNameValidation {
            get {
                return ResourceManager.GetString("FirstNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Contact Center.
        /// </summary>
        internal static string FooterContactCenter {
            get {
                return ResourceManager.GetString("FooterContactCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Contact Left.
        /// </summary>
        internal static string FooterContactLeft {
            get {
                return ResourceManager.GetString("FooterContactLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Contact Right.
        /// </summary>
        internal static string FooterContactRight {
            get {
                return ResourceManager.GetString("FooterContactRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Contact Social Connect.
        /// </summary>
        internal static string FooterContactSocialConnect {
            get {
                return ResourceManager.GetString("FooterContactSocialConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Query Type.
        /// </summary>
        internal static string GeneralQueryType {
            get {
                return ResourceManager.GetString("GeneralQueryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Plus Title.
        /// </summary>
        internal static string GooglePlusTitle {
            get {
                return ResourceManager.GetString("GooglePlusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Plus Redirect Url.
        /// </summary>
        internal static string GooglePlusUrl {
            get {
                return ResourceManager.GetString("GooglePlusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        internal static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hardwares.
        /// </summary>
        internal static string HardwareViewModels {
            get {
                return ResourceManager.GetString("HardwareViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Logo.
        /// </summary>
        internal static string HeaderLogo {
            get {
                return ResourceManager.GetString("HeaderLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock User.
        /// </summary>
        internal static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified ?.
        /// </summary>
        internal static string IsVerified {
            get {
                return ResourceManager.GetString("IsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName must be less 25 word..
        /// </summary>
        internal static string LastNameValidation {
            get {
                return ResourceManager.GetString("LastNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Should be less than 100.
        /// </summary>
        internal static string LengthLessthan100 {
            get {
                return ResourceManager.GetString("LengthLessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Should be less than 50.
        /// </summary>
        internal static string LengthLessthan50 {
            get {
                return ResourceManager.GetString("LengthLessthan50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reason.
        /// </summary>
        internal static string LockedReason {
            get {
                return ResourceManager.GetString("LockedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Version.
        /// </summary>
        internal static string MajorVersion {
            get {
                return ResourceManager.GetString("MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Images.
        /// </summary>
        internal static string MapImages {
            get {
                return ResourceManager.GetString("MapImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Name.
        /// </summary>
        internal static string MaterialName {
            get {
                return ResourceManager.GetString("MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        internal static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type must be select..
        /// </summary>
        internal static string MaterialTypeValidation {
            get {
                return ResourceManager.GetString("MaterialTypeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string MaxSize {
            get {
                return ResourceManager.GetString("MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        internal static string MenuBanner {
            get {
                return ResourceManager.GetString("MenuBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string MenuBasic {
            get {
                return ResourceManager.GetString("MenuBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box 1.
        /// </summary>
        internal static string MenuBox1 {
            get {
                return ResourceManager.GetString("MenuBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box 2.
        /// </summary>
        internal static string MenuBox2 {
            get {
                return ResourceManager.GetString("MenuBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box 3.
        /// </summary>
        internal static string MenuBox3 {
            get {
                return ResourceManager.GetString("MenuBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box 4.
        /// </summary>
        internal static string MenuBox4 {
            get {
                return ResourceManager.GetString("MenuBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        internal static string MenuContinent {
            get {
                return ResourceManager.GetString("MenuContinent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string MenuCountries {
            get {
                return ResourceManager.GetString("MenuCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Centre.
        /// </summary>
        internal static string MenuDataCenter {
            get {
                return ResourceManager.GetString("MenuDataCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Contacts.
        /// </summary>
        internal static string MenuFooter {
            get {
                return ResourceManager.GetString("MenuFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Social Widget.
        /// </summary>
        internal static string MenuFooterWidget {
            get {
                return ResourceManager.GetString("MenuFooterWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Area.
        /// </summary>
        internal static string MenuMapArea {
            get {
                return ResourceManager.GetString("MenuMapArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro Areas.
        /// </summary>
        internal static string MenuMetroArea {
            get {
                return ResourceManager.GetString("MenuMetroArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description.
        /// </summary>
        internal static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords.
        /// </summary>
        internal static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Title.
        /// </summary>
        internal static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Version.
        /// </summary>
        internal static string MicroVersion {
            get {
                return ResourceManager.GetString("MicroVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Version.
        /// </summary>
        internal static string MinorVersion {
            get {
                return ResourceManager.GetString("MinorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string MinSize {
            get {
                return ResourceManager.GetString("MinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be less 25 word..
        /// </summary>
        internal static string NameValidation {
            get {
                return ResourceManager.GetString("NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Continent.
        /// </summary>
        internal static string NoContinent {
            get {
                return ResourceManager.GetString("NoContinent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Countries.
        /// </summary>
        internal static string NoCountries {
            get {
                return ResourceManager.GetString("NoCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Data Centres.
        /// </summary>
        internal static string NoDataCentre {
            get {
                return ResourceManager.GetString("NoDataCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Metro-Areas.
        /// </summary>
        internal static string NoMetroAreas {
            get {
                return ResourceManager.GetString("NoMetroAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Numbers Only.
        /// </summary>
        internal static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string OsType {
            get {
                return ResourceManager.GetString("OsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Image.
        /// </summary>
        internal static string PageImage {
            get {
                return ResourceManager.GetString("PageImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Url.
        /// </summary>
        internal static string PageUrl {
            get {
                return ResourceManager.GetString("PageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be less 6 word..
        /// </summary>
        internal static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid phone number is required..
        /// </summary>
        internal static string PhoneNumberValidation {
            get {
                return ResourceManager.GetString("PhoneNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Notification.
        /// </summary>
        internal static string PopupNotification {
            get {
                return ResourceManager.GetString("PopupNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code..
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid postal code is required..
        /// </summary>
        internal static string PostalCodeValidation {
            get {
                return ResourceManager.GetString("PostalCodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Parts.
        /// </summary>
        internal static string ProductPartViewModels {
            get {
                return ResourceManager.GetString("ProductPartViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Part View Model must be less 50 word..
        /// </summary>
        internal static string ProductPartViewModelsValidation {
            get {
                return ResourceManager.GetString("ProductPartViewModelsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Product..
        /// </summary>
        internal static string ProductPleaseSelect {
            get {
                return ResourceManager.GetString("ProductPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Products.
        /// </summary>
        internal static string ProductViewModels {
            get {
                return ResourceManager.GetString("ProductViewModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product View Models less than 50 word..
        /// </summary>
        internal static string ProductViewModelsValidation {
            get {
                return ResourceManager.GetString("ProductViewModelsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name.
        /// </summary>
        internal static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        internal static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Value.
        /// </summary>
        internal static string PropertyValue {
            get {
                return ResourceManager.GetString("PropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require SSL.
        /// </summary>
        internal static string RequireSSL {
            get {
                return ResourceManager.GetString("RequireSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Type Must be select.
        /// </summary>
        internal static string RoleValidation {
            get {
                return ResourceManager.GetString("RoleValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Serial Number..
        /// </summary>
        internal static string SerialNumberValidation {
            get {
                return ResourceManager.GetString("SerialNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Characters not allowed.
        /// </summary>
        internal static string SpecialChrsNotAllowed {
            get {
                return ResourceManager.GetString("SpecialChrsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select States..
        /// </summary>
        internal static string StatePleaseSelect {
            get {
                return ResourceManager.GetString("StatePleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be less 50 word..
        /// </summary>
        internal static string TitleValidation {
            get {
                return ResourceManager.GetString("TitleValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Title.
        /// </summary>
        internal static string TwitterTitle {
            get {
                return ResourceManager.GetString("TwitterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Redirect Url.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Banner Image.
        /// </summary>
        internal static string UploadBannerImage {
            get {
                return ResourceManager.GetString("UploadBannerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Icon Image.
        /// </summary>
        internal static string UploadIconImage {
            get {
                return ResourceManager.GetString("UploadIconImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Map Area Image.
        /// </summary>
        internal static string UploadMapImages {
            get {
                return ResourceManager.GetString("UploadMapImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a-z or A-Z only entered..
        /// </summary>
        internal static string UserNameValidation {
            get {
                return ResourceManager.GetString("UserNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Website Url.
        /// </summary>
        internal static string Websiteurl1 {
            get {
                return ResourceManager.GetString("Websiteurl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Website Url.
        /// </summary>
        internal static string Websiteurl2 {
            get {
                return ResourceManager.GetString("Websiteurl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Website Url.
        /// </summary>
        internal static string Websiteurl3 {
            get {
                return ResourceManager.GetString("Websiteurl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Type.
        /// </summary>
        internal static string WorkOrderType {
            get {
                return ResourceManager.GetString("WorkOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select work order type..
        /// </summary>
        internal static string WorkOrderTypeValidation {
            get {
                return ResourceManager.GetString("WorkOrderTypeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Status.
        /// </summary>
        internal static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
    }
}
